apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "open-vault-agent-injector.fullname" . }}
  labels:
{{ include "open-vault-agent-injector.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "open-vault-agent-injector.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: open-vault-agent-injector
    namespace: {{ .Release.Namespace }}