apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "open-vault-agent-injector.fullname" . }}
  labels:
{{ include "open-vault-agent-injector.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups:  [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "create", "update", "patch"]
