apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-vault-agent-injector.fullname" . }}
  labels:
{{ include "open-vault-agent-injector.labels" . | indent 4 }}
data:
  injectionconfig.yaml: |
{{ (tpl (.Files.Get "config/injectionconfig.yaml") . ) | indent 4 }}
{{ (tpl (.Files.Glob "config/podlifecyclehooks.yaml").AsConfig . ) | indent 2 }}
{{ (tpl (.Files.Glob "config/*.hcl").AsConfig . ) | indent 2 }}
{{ (tpl (.Files.Glob "config/*.tmpl").AsConfig . ) | indent 2 }}