{{- if eq .Values.mutatingwebhook.cert.generated true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "open-vault-agent-injector.fullname" . }}-cert"
  labels:
{{ include "open-vault-agent-injector.labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: "{{ include "open-vault-agent-injector.fullname" . }}-cert"
    spec:
      restartPolicy: Never
      {{- if .Values.registryKey }}
      imagePullSecrets:
        - name: {{ .Values.registryKey }}
      {{- end }}
      serviceAccountName: open-vault-agent-injector
      containers:
      - name: {{ include "open-vault-agent-injector.fullname" . }}
        image: {{ include "open-vault-agent-injector.image" .Values }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
          - cert
          - -certop=create
          - -certsecretname={{ .Values.mutatingwebhook.cert.secretName }}
          - -certhostnames={{ include "open-vault-agent-injector.service.name" . }},{{ include "open-vault-agent-injector.service.name" . }}.{{ .Release.Namespace }},{{ include "open-vault-agent-injector.service.name" . }}.{{ .Release.Namespace }}.svc
          - -certlifetime={{ .Values.mutatingwebhook.cert.certlifetime }}
          - -cacertfile={{ .Values.mutatingwebhook.cert.cacertfile }}
          - -certfile={{ .Values.mutatingwebhook.cert.certfile }}
          - -keyfile={{ .Values.mutatingwebhook.cert.keyfile }}
          - -logtostderr
          - -stderrthreshold=0
          - -v={{ .Values.mutatingwebhook.loglevel }}
          - 2>&1
{{- end }}